# Change these first
owner: lcmartinezdev # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: acuasoft.com
    url: https://acuasoft.com
  - name: app.tiemppi.com
    url: https://app.tiemppi.com


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: You can check if the server is running by checking this website
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/lcmartinezdev/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
